export const TOOL_LOGOS: Record<string, string> = {
  "Claude": "/logos/claude.svg",
  "Claude Code": "/logos/claude.svg",
  "Claude API": "/logos/claude.svg",
  "Claude Projects": "/logos/claude.svg",
  "ChatGPT": "/logos/chatgpt.png",
  "Cursor": "/logos/cursor.png",
  "Jasper": "/logos/Japser.png",
  "Canva AI (Magic Studio)": "/logos/canva.jpeg",
  "LangChain": "/logos/langchain.png",
  "GitHub Copilot": "/logos/copilot.png",
  "Perplexity": "/logos/perplexity.png",
  "Perplexity Finance": "/logos/perplexity.png",
  "HubSpot AI (Breeze)": "/logos/hubspot.png",
  "Clay": "/logos/clay.png",
  "Gong": "/logos/gong.png",
  "Descript": "/logos/descript.png",
  "Figma AI": "/logos/figma.png",
  "Midjourney": "/logos/midjourney.png",
  "Adobe Firefly": "/logos/adobe-firefly.png",
  "Runway": "/logos/runway.png",
  "Linear": "/logos/linear.png",
  "Notion AI": "/logos/notion.png",
  "Harvey": "/logos/harvey.png",
  "v0 by Vercel": "/logos/vercel.png",
  "Zapier AI": "/logos/zapier.png",
  "Microsoft Copilot for Excel": "/logos/microsoft-copilot.png",
  "Glass AI": "/logos/glass-ai.png",
  "MagicSchool": "/logos/magicschool.png",
  "Khanmigo": "/logos/khanmigo.png",
  "Grammarly": "/logos/grammarly.png",
  "Vercel AI SDK": "/logos/vercel.png",
  "ElevenLabs": "/logos/elevenlabs.png",
  "Gamma": "/logos/gamma.png",
  "Hebbia": "/logos/hebbia.png",
  "Rogo": "/logos/rogo.png",
  "AlphaSense": "/logos/alphasense.png",
  "Abridge": "/logos/abridge.png",
  "Nuance DAX Copilot": "/logos/nuance.png",
  "Suki": "/logos/suki.png",
  "Hippocratic AI": "/logos/hippocratic.png",
  "OpenEvidence": "/logos/openevidence.png",
  "Consensus": "/logos/consensus.png",
  "Diffit": "/logos/diffit.png",
  "Brisk Teaching": "/logos/brisk.png",
  "School AI": "/logos/schoolai.png",
  "Krea": "/logos/krea.png",
  "Ideogram": "/logos/ideogram.png",
  "ComfyUI": "/logos/comfyui.png",
  "Spellbook": "/logos/spellbook.png",
  "Thomson Reuters CoCounsel": "/logos/thomson-reuters.png",
  "Lexis+ AI": "/logos/lexis.png",
  "Ironclad AI": "/logos/ironclad.png",
  "Otter.ai": "/logos/otter.png",
  "Paradox": "/logos/paradox.png",
  "Relay.app": "/logos/relay.png",
  "Dovetail": "/logos/dovetail.png",
};

export const BRAND_COLORS: Record<string, string> = {
  "GitHub Copilot": "bg-[#171717]",
  "Cursor": "bg-[#1F1F1F]",
  "Claude": "bg-[#F5E6D8]",
  "Claude Code": "bg-[#F5E6D8]",
  "Claude API": "bg-[#F5E6D8]",
  "Claude Projects": "bg-[#F5E6D8]",
  "ChatGPT": "bg-[#E8F5EF]",
  "Jasper": "bg-white",
  "Canva AI (Magic Studio)": "bg-white",
  "Perplexity": "bg-[#E8F6F8]",
  "Perplexity Finance": "bg-[#E8F6F8]",
  "HubSpot AI (Breeze)": "bg-[#FFF0EC]",
  "Clay": "bg-[#EEEDFC]",
  "Gong": "bg-[#F0EBFC]",
  "Descript": "bg-[#E8EEFF]",
  "Figma AI": "bg-[#F0E8FF]",
  "Midjourney": "bg-[#F5F5F5]",
  "Adobe Firefly": "bg-[#FFF0E8]",
  "Runway": "bg-[#F5F5F5]",
  "Linear": "bg-[#EDEEF8]",
  "Notion AI": "bg-[#F5F5F5]",
  "Harvey": "bg-[#E8E8F0]",
  "v0 by Vercel": "bg-[#F5F5F5]",
  "Zapier AI": "bg-[#FFF0E8]",
  "Microsoft Copilot for Excel": "bg-[#E8F2EC]",
  "Glass AI": "bg-[#E8F8F5]",
  "MagicSchool": "bg-[#EEEDFC]",
  "Khanmigo": "bg-[#E8F8F2]",
  "Grammarly": "bg-[#E8F8F0]",
  "Vercel AI SDK": "bg-[#F5F5F5]",
  "LangChain": "bg-[#E8F0E8]",
  "ElevenLabs": "bg-[#F5F5F5]",
  "Gamma": "bg-[#F0EBFC]",
};

export function getBrandClass(name: string): string {
  return BRAND_COLORS[name] ?? "bg-bg-elevated";
}

export function getToolLogo(name: string): string | null {
  return TOOL_LOGOS[name] ?? null;
}
